# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=1000)),
                ('image URL', models.CharField(max_length=500)),
                ('error_code', models.CharField(max_length=6)),
            ],
        ),
    ]
